kind: Deployment
apiVersion: apps/v1
metadata:
  name: cart-api-deployment
  namespace: staging-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
        - name: cart-api
          image: docker.io/rempeloliveira/public:cart-api.0.0.2-staging
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: cart-api-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
